export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS';
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const ADD_FRIEND_TO_LIST = 'ADD_FRIEND_TO_LIST';
export const ADD_FRIEND_GROUP = 'ADD_FRIEND_GROUP';
export const ADD_FRIEND = 'ADD_FRIEND';
