export const SET_GROUPS = 'SET_GROUPS';
export const ADD_GROUP_ERROR = 'ADD_GROUP_ERROR';
export const REMOVE_GROUP_ERROR = 'REMOVE_GROUP_ERROR';
export const EDIT_GROUP_ERROR = 'EDIT_GROUP_ERROR';
export const CHANGE_GROUP_ADMIN_ERROR = 'CHANGE_GROUP_ADMIN_ERROR';
export const SHOW_GROUP_FRIENDS_ERROR = 'SHOW_GROUP_FRIENDS_ERROR';
export const ADD_FRIEND_GROUP_ERROR = 'ADD_FRIEND_GROUP_ERROR';



